// This file is AUTO-GENERATED by the docs-site skill.
// Do not edit manually — regenerate by running the skill.
// Uses ?url imports to keep Worker bundle small — content loaded at runtime.

// __IMPORTS__

export interface TopicMeta {
  slug: string
  title: string
  category: 'core' | 'deep-dive' | 'other'
  order: number
  url: string
}

export interface ProjectMeta {
  slug: string
  name: string
  description: string
  topics: TopicMeta[]
  coreTopics: TopicMeta[]
  deepDiveTopics: TopicMeta[]
}

// __PROJECTS_DATA__

export function getProject(slug: string): ProjectMeta | undefined {
  return projects.find((p) => p.slug === slug)
}

export function getTopic(projectSlug: string, topicSlug: string): TopicMeta | undefined {
  const project = getProject(projectSlug)
  if (!project) return undefined
  return project.topics.find((t) => t.slug === topicSlug)
}
