// This file is AUTO-GENERATED by the docs-site skill.
// Do not edit manually — regenerate by running the skill.
// Titles are extracted from markdown H1 headings at generation time.

import topic01 from '../../../topics/01-project-basic-info.md?url'
import topic02 from '../../../topics/02-project-structure.md?url'
import topic03 from '../../../topics/03-tech-stack.md?url'
import topic04 from '../../../topics/04-core-features.md?url'
import topic05 from '../../../topics/05-architecture-design.md?url'
import topic06 from '../../../topics/06-code-quality.md?url'
import topic07 from '../../../topics/07-documentation-quality.md?url'
import topic08 from '../../../topics/08-project-activity.md?url'
import topic09 from '../../../topics/09-strengths-weaknesses.md?url'
import topic10 from '../../../topics/10-use-cases.md?url'
import topic11 from '../../../topics/11-learning-value.md?url'
import topic12 from '../../../topics/12-summary.md?url'
import dd01 from '../../../topics/deep-dive-01-gateway-protocol.md?url'
import dd02 from '../../../topics/deep-dive-02-auto-reply-pipeline.md?url'
import dd03 from '../../../topics/deep-dive-03-session-jsonl-storage.md?url'
import dd04 from '../../../topics/deep-dive-04-tool-policy.md?url'
import dd05 from '../../../topics/deep-dive-05-plugin-jiti-loading.md?url'

export interface TopicMeta {
  slug: string
  title: string
  category: 'core' | 'deep-dive'
  order: number
  url: string
}

const all: TopicMeta[] = [
  // __TITLE__: Extract from H1 heading of each .md file at generation time
  { slug: '01-project-basic-info', title: 'Project Basic Information', category: 'core', order: 1, url: topic01 },
  { slug: '02-project-structure', title: 'Project Structure', category: 'core', order: 2, url: topic02 },
  { slug: '03-tech-stack', title: 'Tech Stack', category: 'core', order: 3, url: topic03 },
  { slug: '04-core-features', title: 'Core Features', category: 'core', order: 4, url: topic04 },
  { slug: '05-architecture-design', title: 'Architecture Design', category: 'core', order: 5, url: topic05 },
  { slug: '06-code-quality', title: 'Code Quality', category: 'core', order: 6, url: topic06 },
  { slug: '07-documentation-quality', title: 'Documentation Quality', category: 'core', order: 7, url: topic07 },
  { slug: '08-project-activity', title: 'Project Activity', category: 'core', order: 8, url: topic08 },
  { slug: '09-strengths-weaknesses', title: 'Strengths & Weaknesses', category: 'core', order: 9, url: topic09 },
  { slug: '10-use-cases', title: 'Use Cases', category: 'core', order: 10, url: topic10 },
  { slug: '11-learning-value', title: 'Learning Value', category: 'core', order: 11, url: topic11 },
  { slug: '12-summary', title: 'Summary', category: 'core', order: 12, url: topic12 },
  { slug: 'deep-dive-01-gateway-protocol', title: 'Deep Dive: Gateway Protocol', category: 'deep-dive', order: 1, url: dd01 },
  { slug: 'deep-dive-02-auto-reply-pipeline', title: 'Deep Dive: Auto Reply Pipeline', category: 'deep-dive', order: 2, url: dd02 },
  { slug: 'deep-dive-03-session-jsonl-storage', title: 'Deep Dive: Session JSONL Storage', category: 'deep-dive', order: 3, url: dd03 },
  { slug: 'deep-dive-04-tool-policy', title: 'Deep Dive: Tool Policy', category: 'deep-dive', order: 4, url: dd04 },
  { slug: 'deep-dive-05-plugin-jiti-loading', title: 'Deep Dive: Plugin JITI Loading', category: 'deep-dive', order: 5, url: dd05 },
]

export const coreTopics = all.filter((t) => t.category === 'core')
export const deepDiveTopics = all.filter((t) => t.category === 'deep-dive')
export const topics = all

export function getTopicBySlug(slug: string): TopicMeta | undefined {
  return all.find((t) => t.slug === slug)
}
